### ISSUE TITLE
🎨 Arreglar texto en Invoice Item

### ISSUE THREAD

**Issue by AllegriM** [nsdonato/front-invoices#39]
### Arreglar el color del texto en dark mode que muestra el monto del Invoice.

![Image](https://user-images.githubusercontent.com/92539373/214981287-4a2b09d2-87c0-4651-99ab-881c5b6b1379.png)

**Como se deberia ver:** Blanco.

**Como se ve:** Negro.

**Comment by nsdonato** [comment]
Fachera, el titulo lo tenemos que poner en castellano.
Faltan los labels, en este caso el de bug.
Y una prioridad, puede ser media, ya que el texto en si, no se ve
