### ISSUE TITLE
Configurar auto assign pr en el pipeline

### ISSUE THREAD

**Issue by nsdonato** [nsdonato/front-invoices#5]
COMO desarrollador QUIERO poder automatizar la asignación del pr al creador del mismo PARA que quede indentificado el responsable y no haya dos personas haciendo lo mismo. 

Definición de hecho:
Que se pueda autoasignar el PR en el pipeline del ci/cd

**Comment by maadeval** [comment]
Hola!! 👋 Revisando los anteriores `Works` de las Actions detecté que no han ocurrido errores en la asignación de PRs.

## 💡 Posibles casos de uso:
La tarea se pudo haber asignado al proyecto `frontend` en lugar de `backend`.  

> Esto es una posibilidad, aun así revisando el repo de `backend` no encontré error en la asignación de PRs sino en el Linter. https://github.com/nsdonato/back-invoices/actions/runs/3915768251. Esto en ateriores PRs ya que actualmente está desactivado.

## ⚡️ Conclusión

Teniendo en cuenta esto y la prioridad que tiene la tarea en el [Backlog](https://github.com/users/nsdonato/projects/4/views/1?pane=issue&itemId=18121545) decidí mantener el estado de la Issue en `Open` y evaluar su estado en la futura daily con el equipo 🚀

**Comment by nsdonato** [comment]
Sip, me equivoqué 😅, es de back 😬, le podemos cambiar la etiqueta y volver al backlog o si consideras que podes seguirla, toda tuya <3

**Comment by maadeval** [comment]
Holis! 👋  Muchas gracias por comentar!! 😊

Estuve probando en cambiar la etiqueta de `frontend` a `backend` pero este cambio solo se genera a nivel de etiqueta y no de repo.

## 👀 Consecuencias?

- La Issue no se puede transladar del repo de `frontend` al de `backend`.
- La PR asociada a la Issue está linkeada con el repo de `frontend`.
- No se puede asociar una PR del repo de `backend` a esta Issue.

## ✅ Soluciones

Con este contexto considero:
Dar por cerrada la Issue y dejo abierta la posibilidad de generar una nueva en el repo de Backend ✨ (ya que en `frontend` estaba funcionando correctamente en las ultimas asignaciones).

A su vez, esa nueva Issue popongo que contenga como tarea descomentar el `pipeline` y centrarse en solucionar el error de `Linter` y posteriores. Ya que en sus últimos works antes de descomentarlo, la asignación de PR funcionó correctamente 🚀

Como siempre, son propuestas! Así que no debe tomarse como una tarea a seguir y siempre se puede llevar por otro caminos y comentar 🧭
