### ISSUE TITLE
Agregar Light/Dark mode

### ISSUE THREAD

**Issue by nsdonato** [nsdonato/front-invoices#6]
COMO desarrollador QUIERO poder agregar light/dark mode PARA poder cumplir con el Design System.

Definición de hecho:

- [x] Se ve correctamente en todos los diseños (desktop, tablet, mobile)
- [x] Tiene su test correspondiente
- [x] Cumple con el Design System

Que se pueda ver la app en ligth o dark mode. Podes hacer un botón (no necesariamente estilado, sino más bien para las pruebas del cambio de theme)

**Comment by techwithmat** [comment]
Implementación añadida y mergeada. Número de tarea [#36](https://github.com/nsdonato/front-invoices/pull/36).
