### ISSUE TITLE
Crear component NavBar

### ISSUE THREAD

**Issue by nsdonato** [nsdonato/front-invoices#7]
COMO desarrollador QUIERO crear el componente NavBar PARA poder mostrar lo diseñado en el Design System.

Definición de hecho:
Que se pueda ver el NavBar, no tiene comportamiento (el botón de cambio de theme no esta comprendido en la tarea)

- [x] Se ve correctamente en todos los diseños (desktop, tablet, mobile)
- [x] Tiene su test correspondiente
- [x] Cumple con el Design System

![image](https://user-images.githubusercontent.com/7875216/212570252-4a8aa99a-88ac-4154-9e43-b919d382e66d.png)

**Comment by Boguita** [comment]
Holu, el NavBar lo dejamos siempre arriba? o para Desktop lo pongo al igual que el diseño de Figma(vertical)?
